apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-group-a
  labels:
    app: nginx-deployment-group-a
spec:
  replicas: 3
  selector:
    matchLabels:
      podGroup: "A"
      minAvailable: "3"
  template:
    metadata:
      labels:
        podGroup: "A"
        minAvailable: "3"
    spec:
      schedulerName: my-scheduler
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "100Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-group-b
  labels:
    app: nginx-deployment-group-b
spec:
  replicas: 2
  selector:
    matchLabels:
      podGroup: "B"
      minAvailable: "3"
  template:
    metadata:
      labels:
        podGroup: "B"
        minAvailable: "3"
    spec:
      schedulerName: my-scheduler
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "100Mi"
    